### ISSUE TITLE
Query.mongodbResolvers defined in resolvers, but not in schema

### ISSUE THREAD

**Issue by heipacker** [EOS-Nation/eosio-graphql#3]
when execute this command 
nohup npm start &

**Comment by DenisCarriere** [comment]
@heipacker I've had this error happen a few commits ago, however I've just deployed it and everything seems to work just fine.

Which version of NodeJS are you running with?

I'm using:

```
$ node -v
v8.11.3
```

Try doing a clean install and `npm start` again.

```
$ git pull
$ rm -r node_modules
$ npm install
$ npm start
```

**Comment by heipacker** [comment]
@DenisCarriere  
$ node -v
v8.11.3
and i try to clean  install, the same error occur

**Comment by odarboe** [comment]
@DenisCarriere 

I have updated my node version to 8.11.3 but still getting the same issue. I believe it has to do with mongodb setup in the eosio-graphql project. 
See logs
![screenshot from 2018-08-26 11-30-23](https://user-images.githubusercontent.com/1871493/44626841-25a09d80-a924-11e8-9b7d-b9d7ccaf25ad.png)

**Comment by DenisCarriere** [comment]
@odarboe strange, how did you install the library?

```
$ npm install
```

I'll look into.. seems like it's missing the module `@types/mongodb`

**Comment by odarboe** [comment]
Hi @DenisCarriere  Yes I have tried cleaning and installing many times. I also specifically install mongodb and verified that the instance of mongod running without problem. it still gave me the same error.
